# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0002_lesson_part_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watcher',
            name='info',
        ),
        migrations.AddField(
            model_name='watcher',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
