# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('watcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shedule.Watcher')),
            ],
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='history',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='info',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='planet',
            old_name='history',
            new_name='info',
        ),
        migrations.AddField(
            model_name='bg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='watch',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='coming_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_st_nab',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='work',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bg',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/BG/'),
        ),
        migrations.AlterField(
            model_name='bg',
            name='last_st_nab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Person'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.BG'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Planet'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='result',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/Person/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.Planet'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/Planet/'),
        ),
        migrations.AddField(
            model_name='mission',
            name='points',
            field=models.ManyToManyField(blank=True, to='archive.Point'),
        ),
    ]
