# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20170324_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='were_burn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='coming_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
