# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20170326_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='points',
        ),
        migrations.AddField(
            model_name='point',
            name='mission',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='archive.Mission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='mission_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.Watcher'),
        ),
    ]
