# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20170819_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='work',
            new_name='work_before',
        ),
    ]
