# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20170819_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='mission_name',
        ),
        migrations.AlterField(
            model_name='point',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archive.Mission'),
        ),
        migrations.AlterField(
            model_name='point',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='point',
            name='watcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shedule.Watcher'),
        ),
    ]
