# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_mission_planet_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bg',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bg',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='published_date',
        ),
    ]
