# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_auto_20180305_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='planet_text',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='bg',
        ),
        migrations.AddField(
            model_name='mission',
            name='bg',
            field=models.ManyToManyField(blank=True, related_name='missions', to='archive.BG'),
        ),
        migrations.RemoveField(
            model_name='mission',
            name='planet',
        ),
        migrations.AddField(
            model_name='mission',
            name='planet',
            field=models.ManyToManyField(blank=True, related_name='missions', to='archive.Planet'),
        ),
    ]
