# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20180315_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='planet_text',
            field=models.TextField(null=True),
        ),
    ]
