# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_mission_planet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='target',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='watch',
            field=models.IntegerField(null=True),
        ),
    ]
