# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20180319_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='planet_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
