# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='clas',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.IntegerField(),
        ),
    ]
